In [9]:
import pandas as pd
import numpy as np
import random

data=pd.read_csv('dataset.csv')
result=list(data['pktcount']/data['dur'])
data['pktCount/dur']=result
result=list(data['bytecount']/data['dur'])
data['byteCount/dur']=result

# Replacing infinite with nan
data.replace([np.inf, -np.inf], np.nan, inplace=True)
  
# Dropping all the rows with nan values
data.dropna(inplace=True)

for i in data.index:
    if data.at[i, 'switch'] < random.randint(1, 10):
        data.at[i, 'switch'] += random.randint(1, 7)
    if data.at[i, 'dur'] < random.randint(1, 1881):
        data.at[i, 'dur'] += random.randint(1, 661)
    if data.at[i, 'pktcount'] < random.randint(53000, 200000):
        data.at[i, 'pktcount'] += random.randint(20000, 40000)
    if data.at[i, 'pktcount'] > random.randint(53000, 200000):
        data.at[i, 'pktcount'] -= random.randint(10000, 50000)
    if data.at[i, 'flows'] < random.randint(4, 10):
        data.at[i, 'flows'] += random.randint(1, 10)

s_dataset = data.groupby('label').get_group(0)
m_dataset = data.groupby('label').get_group(1)
s_dataset = s_dataset.drop(['dt','src','dst','label'], axis=1)
m_dataset = m_dataset.drop(['dt','src','dst','label'], axis=1)
s_dataset = pd.get_dummies(s_dataset)
m_dataset = pd.get_dummies(m_dataset)

def randomd(df, size):
    x = random.sample(list(df.index), k=size)
    d = df.loc[x]
    return d

def gen(m):
    m *= 200
    s = 20000-m
    m_data = randomd(m_dataset, m)
    s_data = randomd(s_dataset, s)
    fdata = pd.concat([m_data, s_data], ignore_index = True)
    fdata.to_csv(f"data{m}.csv", index=False)
    
gen(50)
gen(60)
gen(70)
data.describe()

,dt,switch,pktcount,bytecount,dur,dur_nsec,tot_dur,flows,packetins,pktperflow,...,Pairflow,port_no,tx_bytes,rx_bytes,tx_kbps,rx_kbps,tot_kbps,label,pktCount/dur,byteCount/dur
count,103507.000000,103507.000000,103507.000000,1.035070e+05,103507.000000,1.035070e+05,1.035070e+05,103507.000000,103507.000000,103507.000000,...,103507.000000,103507.000000,1.035070e+05,1.035070e+05,103507.000000,103507.000000,103507.000000,103507.000000,103507.000000,103507.000000
mean,17997.346943,6.518506,71766.415566,3.813851e+07,597.133063,4.613735e+08,3.235481e+11,9.149062,5839.179456,6414.635744,...,0.604181,2.337455,9.388806e+07,9.391601e+07,1004.058885,1004.098428,2008.157313,0.389375,252.017792,188156.047010
std,11963.141732,2.638770,41119.794085,4.877646e+07,312.324280,2.768589e+08,2.836776e+11,3.160443,5243.078948,7187.717686,...,0.489028,1.082924,1.522918e+08,1.332648e+08,2428.584644,2054.970744,3144.913299,0.487611,188.222092,205067.884489
min,2488.000000,1.000000,5992.000000,0.000000e+00,4.000000,0.000000e+00,1.024000e+09,3.000000,32.000000,-130933.000000,...,0.000000,1.000000,2.527000e+03,8.560000e+02,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,7128.000000,4.000000,35015.500000,7.947800e+04,365.000000,2.340000e+08,1.300000e+11,7.000000,2647.000000,29.000000,...,0.000000,1.000000,4.812000e+03,3.539000e+03,0.000000,0.000000,0.000000,0.000000,0.977528,95.797753
50%,11965.000000,6.000000,64703.000000,6.443094e+06,567.000000,4.180000e+08,2.530000e+11,9.000000,3742.000000,8314.000000,...,1.000000,2.000000,4.609657e+06,1.421994e+07,0.000000,0.000000,4.000000,0.000000,298.455556,29671.707809
75%,29982.000000,8.000000,102112.500000,7.600244e+07,781.000000,7.020000e+08,4.130000e+11,11.000000,7916.000000,10015.000000,...,1.000000,3.000000,1.356555e+08,1.439286e+08,255.000000,557.000000,3838.000000,1.000000,434.847403,352350.357675
max,42935.000000,16.000000,249566.000000,1.471280e+08,2312.000000,9.990000e+08,1.880000e+12,19.000000,26224.000000,19190.000000,...,1.000000,5.000000,1.269982e+09,9.905962e+08,20580.000000,16577.000000,20580.000000,1.000000,2383.000000,673712.000000